In [1]:
import os
import pandas as pd
import numpy as np
from PIL import Image

# Load metadata
metadata_path = "dataset/HAM10000_metadata.csv"
metadata = pd.read_csv(metadata_path)

# Define image folder path
image_folder_path = "dataset/HAM10000_new_folder"

# Initialize lists to store images and labels
images = []
labels = []

# Loop through the metadata and load images
for index, row in metadata.iterrows():
    image_id = row['image_id']
    label = row['dx']
    
    # Construct image file path
    image_path = os.path.join(image_folder_path, f"{image_id}.jpg")
    
    # Load image and convert to NumPy array
    image = np.array(Image.open(image_path))
    
    # Append image and label to the lists
    images.append(image)
    labels.append(label)

# Convert lists to NumPy arrays
images = np.array(images)
labels = np.array(labels)

# Define the dataset structure as a tuple
dataset = (images, labels)

# Print the first two elements of the dataset for verification
print(dataset[0][:2])  # Print the first two images
print(dataset[1][:2])  # Print the corresponding labels


[[[[188 147 191]
   [186 148 189]
   [187 150 191]
   ...
   [196 155 171]
   [197 156 170]
   [197 157 168]]

  [[186 149 193]
   [187 152 194]
   [189 153 191]
   ...
   [194 156 169]
   [195 159 169]
   [192 159 168]]

  [[185 148 192]
   [189 152 195]
   [190 153 196]
   ...
   [196 155 169]
   [198 157 171]
   [194 156 169]]

  ...

  [[157 124 155]
   [156 121 154]
   [159 124 154]
   ...
   [177 146 161]
   [176 144 159]
   [175 141 155]]

  [[155 122 151]
   [156 123 154]
   [156 123 152]
   ...
   [178 147 163]
   [175 144 159]
   [175 142 159]]

  [[154 119 151]
   [153 120 149]
   [154 121 152]
   ...
   [176 147 167]
   [175 147 161]
   [173 143 155]]]


 [[[ 25  15  23]
   [ 25  14  22]
   [ 25  14  22]
   ...
   [ 62  38  64]
   [ 58  38  63]
   [ 59  39  64]]

  [[ 25  12  22]
   [ 23  12  20]
   [ 26  15  23]
   ...
   [ 62  39  67]
   [ 61  38  64]
   [ 60  36  62]]

  [[ 21  14  22]
   [ 24  12  24]
   [ 25  12  21]
   ...
   [ 60  37  65]
   [ 62  37  67]
   [ 61  37